/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Customers {
  address: string | null;
  city: string | null;
  country: string | null;
  customer_id: Generated<number | null>;
  email: string;
  first_name: string;
  last_name: string;
  password_hash: string;
  postal_code: string | null;
}

export interface OrderItems {
  order_id: number;
  order_item_id: Generated<number | null>;
  price_at_order: number;
  product_id: number;
  quantity: number;
}

export interface Orders {
  customer_id: number;
  order_date: string;
  order_id: Generated<number | null>;
  status: string;
  total_amount: number;
}

export interface Products {
  category: string | null;
  description: string | null;
  name: string;
  price: number;
  product_id: Generated<number | null>;
  stock_quantity: number;
}

export interface Reviews {
  comment: string | null;
  customer_id: number;
  product_id: number;
  rating: number;
  review_date: string;
  review_id: Generated<number | null>;
}

export interface DB {
  Customers: Customers;
  OrderItems: OrderItems;
  Orders: Orders;
  Products: Products;
  Reviews: Reviews;
}
